nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:8080']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Authorization']
    paths:
        '^/api/':
            allow_origin: ['http://localhost:8080']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
