controllers:
    resource: '../src/Controller/'
    type: attribute

admin:
    resource: '../src/Controller/Admin'
    type: attribute

home:
    resource: '../src/Controller/HomeController.php'
    type: attribute
    
api_login:
    path: /api/login
    controller: App\Controller\SecurityController::apiLogin
    methods: [POST]