controllers:
    resource: '../src/Controller/'
    type: attribute

admin:
    resource: '../src/Controller/Admin'
    type: attribute

home:
    resource: '../src/Controller/HomeController.php'
    type: attribute

api_login:
    path: /api/login
    controller: App\Controller\SecurityController::apiLogin
    methods: [POST]

<<<<<<< HEAD
# Routes pour CommissionController
commissions:
    resource: '../src/Controller/CommissionController.php'
    type: attribute

# Routes pour PostController
posts:
    resource: '../src/Controller/PostController.php'
    type: attribute

# Routes pour PrivateMessageController
private_messages:
    resource: '../src/Controller/PrivateMessageController.php'
    type: attribute
=======
api_user:
    path: /api/user
    controller: App\Controller\SecurityController::getUserInfo
    methods: [GET]
>>>>>>> origin/Test-Lucas
