controllers:
    resource: '../src/Controller/'
    type: attribute

admin:
    resource: '../src/Controller/Admin'
    type: attribute

home:
    resource: '../src/Controller/HomeController.php'
    type: attribute
    