controllers:
    resource: '../src/Controller/'
    type: attribute

admin:
    resource: '../src/Controller/Admin'
    type: attribute

home:
    resource: '../src/Controller/HomeController.php'
    type: attribute
# Routes pour CommissionController
commissions:
    resource: '../src/Controller/CommissionController.php'
    type: attribute

# Routes pour PostController
posts:
    resource: '../src/Controller/PostController.php'
    type: attribute

# Routes pour PrivateMessageController
private_messages:
    resource: '../src/Controller/PrivateMessageController.php'
    type: attribute
